[package]
name = "Pen_3D_Engine"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
rand = "0.10.3"
indexmap = "2.14.2"
kiddo = "5.3.2"
image = "0.25.9"
atomic_float = "1.1.0"
tokio = { version = "1.53.2", features = ["full"] }
wgpu = "30.0.1"
env_logger = "0.11.11"
pollster = "1.0.1"
winit = "0.30.13"
bytemuck = { version = "1.25.2", features = ["derive"] }
arc-swap = "1.9.2"
glam = "0.34.1"